// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEJlLu34qGBcLk_dJMbe4sBX2E-hg2WA',
    appId: '1:271733983894:web:91ad9c3c22af7479dad0b7',
    messagingSenderId: '271733983894',
    projectId: 'lofo-usu-b8800',
    authDomain: 'lofo-usu-b8800.firebaseapp.com',
    storageBucket: 'lofo-usu-b8800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaedjVcaiIlAQKMUKfmPcZZViUwRxG4fE',
    appId: '1:271733983894:android:f64942072687e3c1dad0b7',
    messagingSenderId: '271733983894',
    projectId: 'lofo-usu-b8800',
    storageBucket: 'lofo-usu-b8800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-vbf5A7NVOpHWJIxGYLEtgVw5y2VT-g',
    appId: '1:271733983894:ios:274d62c1c9fe8df8dad0b7',
    messagingSenderId: '271733983894',
    projectId: 'lofo-usu-b8800',
    storageBucket: 'lofo-usu-b8800.firebasestorage.app',
    iosBundleId: 'com.example.lofo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-vbf5A7NVOpHWJIxGYLEtgVw5y2VT-g',
    appId: '1:271733983894:ios:274d62c1c9fe8df8dad0b7',
    messagingSenderId: '271733983894',
    projectId: 'lofo-usu-b8800',
    storageBucket: 'lofo-usu-b8800.firebasestorage.app',
    iosBundleId: 'com.example.lofo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJEJlLu34qGBcLk_dJMbe4sBX2E-hg2WA',
    appId: '1:271733983894:web:2fb80975cb5652e2dad0b7',
    messagingSenderId: '271733983894',
    projectId: 'lofo-usu-b8800',
    authDomain: 'lofo-usu-b8800.firebaseapp.com',
    storageBucket: 'lofo-usu-b8800.firebasestorage.app',
  );

}